version: '3.8'

services:
  # --- TẦNG HẠ TẦNG (Cơ sở dữ liệu & Messaging) ---
  mysql-db:
    image: mysql:8.0
    container_name: mysql_noah
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: web_store
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5  
    networks:
      - noah-network

  postgres-db:
    image: postgres:15
    container_name: postgres_noah
    environment:
      POSTGRES_PASSWORD: pg_password
      POSTGRES_DB: finance
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10  
    networks:
      - noah-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_noah
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - noah-network

  # --- MODULE 2: ORDER PIPELINE ---
  order-api:
    build: ./order_api
    container_name: order_api_service
    depends_on:
      - mysql-db
      - rabbitmq
    networks:
      - noah-network

  order-worker:
    build: ./order_worker
    container_name: order_worker_service
    depends_on:
      postgres-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      mysql-db:
        condition: service_healthy
    networks:
      - noah-network
    environment:
      - DB_HOST=mysql-db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=noah_store
    volumes:
      - ./inventory-sync/input:/app/input
      - ./inventory-sync/processed:/app/processed

  # ==========================================
  # 3. KONG GATEWAY & REALTIME SERVICE
  # ==========================================
  realtime-service:
    build: ./realtime-service
    ports:
      - "8002:8001"
    networks:
      - noah-network

  kong-database:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong"]
      interval: 5s
      timeout: 5s
      retries: 5  
    image: postgres:13
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    networks:
      - noah-network

  kong-migration:
    image: kong:3.0
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
    depends_on:
      kong-database:
        condition: service_healthy
    networks:
      - noah-network

  kong:
    image: kong:3.0
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
  
      # LOG
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr

      # PORT CHUẨN
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./realtime-service/kong.yml:/kong/kong.yml      
    ports:
      - "8000:8000"   
      - "8001:8001"   
    depends_on:
      - realtime-service
    networks:
      - noah-network


networks:
  noah-network:
    driver: bridge