services:
  order-api:
    build:
      context: ./realtime-service
    restart: always
    networks:
      - backend

  kong:
    image: kong:3.0
    container_name: kong
    restart: always
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
    volumes:
      - ./realtime-service/kong.yml:/kong/kong.yml
    ports:
      - "8000:8000"
    networks:
      - backend

networks:
  backend: