services:
  # ==========================================
  # 1. HẠ TẦNG DATABASE & MESSAGING
  # ==========================================
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: noah_store
    ports:
      - "3307:3306"
    volumes:
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 600s
    networks:
      - noah-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - noah-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - noah-network

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: pg_password
      POSTGRES_DB: finance
    ports:
      - "5433:5432"
    networks:
      - noah-network

  # ==========================================
  # 2. MODULE 1: ĐỒNG BỘ KHO
  # ==========================================
  legacy-adapter:
    build: ./inventory-sync
    container_name: legacy-adapter
    depends_on:
      - mysql-db
      - redis
    environment:
      - DB_HOST=mysql-db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=noah_store
      - INPUT_DIR=/app/input
      - PROCESSED_DIR=/app/processed
      - POLL_SECONDS=5
    volumes:
      - ./inventory-sync/input:/app/input
      - ./inventory-sync/processed:/app/processed
    restart: unless-stopped
    networks:
      - noah-network

  # ==========================================
  # 3. MODULE 2: ORDER PIPELINE
  # ==========================================
  order-api:
    build: ./order_api
    container_name: order-api
    #ports:
    # - "8080:8000"
    depends_on:
      - mysql-db
      - rabbitmq
      - redis
    networks:
      - noah-network

  order-worker:
    build: ./order_worker
    container_name: order-worker
    depends_on:
      - mysql-db
      - postgres-db
      - rabbitmq
    networks:
      - noah-network

  # ==========================================
  # 4. MODULE 3: REPORT SERVICE
  # ==========================================
  report-service:
    build: ./report-service
    container_name: report-service
    #ports:
    #  - "7000:7000"
    depends_on:
      - mysql-db
    networks:
      - noah-network

  # ==========================================
  # 5. REALTIME SERVICE
  # ==========================================
  realtime-service:
    build: ./realtime-service
    container_name: realtime-service
    #ports:
    #  - "8001:8001"
    networks:
      - noah-network

  # ==========================================
  # 6. KONG GATEWAY
  # ==========================================

  kong:
    image: kong:3.0
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./realtime-service/kong.yml:/kong/kong.yml
    depends_on:
      - order-api
      - report-service
    networks:
      - noah-network

  # ==========================================
  # 7. OPTION 5: STOREFRONT
  # ==========================================
  storefront:
    build: ./storefront
    container_name: storefront
    ports:
      - "3000:80"
    networks:
      - noah-network

networks:
  noah-network:
    driver: bridge